version: '3'

services:
  postgres:
    image: 'postgres:16.2'
    container_name: 'java-postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_DB=postgres'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080